var words_1 = [
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
    'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
    'u', 'v', 'x', 'y', 'z'
]
var words_2 = ["an", "as", "at", "be", "by", "do", "go", "he", "hi", "if", "in", "is", "it", "me", "no", "of", "on", "or", "so", "to", "up", "us"];
var words_3 = [
    "cat", "dog", "bat", "rat", "hat", "mat", "car", "bar", "far", "jar",
    "run", "fun", "sun", "gun", "pen", "ten", "men", "hen", "pin", "win",
    "box", "fox", "lox", "toy", "boy", "joy", "day", "say", "way", "pay",
    "red", "bed", "fed", "led", "big", "dig", "fig", "pig", "wig", "zip",
    "add", "bad", "dad", "mad", "sad", "top", "hop", "mop", "pop", "sop",
    "cut", "gut", "nut", "put", "bit", "fit", "hit", "kit", "sit", "tip",
    "ask", "bus", "cup", "dip", "eat", "fan", "gap", "ham", "ice", "jam",
    "key", "law", "map", "net", "odd", "old", "own", "pad", "raw", "sea",
    "tea", "use", "van", "war", "yes", "zoo", "arm", "bet", "cry", "dry",
    "eye", "fly", "get", "hot", "ink", "lip", "mix", "new", "off", "one",
    "out", "pat", "pet", "pot", "rid", "rob", "rod", "rot", "rug", "set",
    "shy", "sip", "sky", "son", "tan", "tap", "tar", "tie", "tin", "ton",
    "try", "two", "vet", "web", "wet", "who", "why", "yet", "air", "ant",
    "ape", "arc", "art", "bag", "ban", "beg", "bin", "bow", "bud", "bun",
    "cap", "cob", "cod", "cog", "con", "cop", "cow", "dam", "den", "dew",
    "dim", "doe", "dot", "due", "dug", "dye", "ear", "egg", "elm", "end",
    "eve", "fad", "fee", "few", "fin", "fir", "fix", "foe", "fog", "fur",
    "gal", "gas", "gel", "gem", "gin", "got", "gum", "hag", "hem", "her",
    "hid", "him", "hip", "his", "hoe", "hog", "hub", "hue", "hug", "hum",
    "hut", "ill", "ion", "ivy", "jab", "jag", "jog", "jot", "jug", "kin",
    "lad", "lag", "lap", "lay", "leg", "let", "lid", "lie", "log", "lot",
    "low", "lug", "man", "mar", "met", "mid", "mob", "mud", "mug", "nag",
    "nap", "nod", "nor", "not", "now", "oak", "oar", "oat", "oil", "opt",
    "orb", "ore", "our", "owl", "pan", "par", "paw", "pea", "peg", "per",
    "pie", "pit", "ply", "pod", "pro", "pub", "pup", "rag", "ram", "ran",
    "ray", "rib", "rig", "rim", "rip", "row", "rub", "rue", "rum", "rut",
    "sap", "saw", "sew", "she", "sin", "sir", "six", "ski", "sly", "sod",
    "spa", "spy", "sub", "sue", "sum", "tab", "tag", "tax", "the", "toe",
    "too", "tub", "tug", "urn", "wad", "wag", "was", "wax", "woe", "won",
    "yap", "yea", "yen", "you", "zap", "zen"
]
var words_4_to_6 = [
    "apple", "bread", "chair", "table", "house", "water", "river", "stone", "cloud", "forest",
    "smile", "laugh", "dance", "music", "piano", "guitar", "violin", "drums", "singer", "stage",
    "light", "shadow", "dream", "sleep", "awake", "think", "learn", "teach", "study", "books",
    "paper", "write", "paint", "color", "brush", "canvas", "sculpt", "stone", "metal", "glass",
    "earth", "planet", "stars", "galaxy", "space", "rocket", "orbit", "moon", "solar", "comet",
    "ocean", "waves", "beach", "sandy", "shell", "coral", "fishy", "shark", "whale", "dolphin",
    "tiger", "lion", "bear", "wolf", "deer", "eagle", "hawk", "owl", "snake", "spider",
    "horse", "camel", "zebra", "goat", "sheep", "chicken", "rooster", "duck", "goose", "turkey",
    "fruit", "grape", "lemon", "orange", "berry", "peach", "plum", "mango", "cherry", "apple",
    "bread", "cheese", "pizza", "pasta", "salad", "soup", "steak", "fries", "cake", "cookie",
    "sugar", "honey", "spice", "sauce", "juice", "coffee", "teacup", "milk", "cream", "butter",
    "shirt", "pants", "shoes", "socks", "jacket", "sweater", "scarf", "gloves", "hat", "belt",
    "watch", "clock", "phone", "laptop", "screen", "mouse", "keyboard", "cable", "power", "radio",
    "travel", "plane", "train", "bus", "car", "bike", "road", "path", "bridge", "tunnel",
    "city", "town", "village", "street", "park", "garden", "fountain", "statue", "bench", "lamp",
    "money", "coin", "bill", "wallet", "bank", "card", "cash", "check", "price", "trade",
    "work", "job", "office", "desk", "chair", "file", "paper", "pen", "note", "meeting",
    "play", "game", "sport", "ball", "team", "goal", "score", "run", "jump", "swim",
    "love", "hate", "fear", "hope", "trust", "faith", "peace", "anger", "joy", "sadness",
    "time", "hour", "minute", "second", "day", "week", "month", "year", "season", "clock",
    "north", "south", "east", "west", "map", "compass", "guide", "trail", "mountain", "valley",
    "rain", "snow", "wind", "storm", "thunder", "lightning", "fog", "mist", "sunny", "cloudy",
    "cold", "warm", "hot", "cool", "freeze", "melt", "burn", "glow", "shine", "dark",
    "blue", "green", "yellow", "red", "purple", "pink", "black", "white", "gray", "brown",
    "fast", "slow", "quick", "speed", "rush", "calm", "quiet", "loud", "soft", "hard",
    "big", "small", "tall", "short", "wide", "narrow", "long", "tiny", "huge", "little",
    "good", "bad", "great", "poor", "rich", "happy", "sad", "angry", "kind", "mean",
    "open", "close", "start", "stop", "begin", "end", "rise", "fall", "lift", "drop",
    "push", "pull", "throw", "catch", "hold", "break", "fix", "build", "create", "destroy",
    "find", "lose", "search", "hide", "show", "tell", "ask", "answer", "call", "wait",
    "walk", "run", "jump", "climb", "crawl", "fly", "drive", "ride", "sail", "swim",
    "food", "drink", "taste", "smell", "touch", "hear", "see", "look", "watch", "listen",
    "life", "death", "birth", "grow", "age", "change", "move", "stay", "leave", "return"
]

var words_8_or_more = [
    "beautiful", "adventure", "delicious", "treasure", "knowledge", "fantastic", "discovery", "inspiring",
    "challenge", "mountains", "education", "wonderful", "celebrate", "friendship", "dangerous", "impossible",
    "landscape", "mysterious", "technology", "brilliant", "happiness", "creativity", "experience", "dedication",
    "wilderness", "invention", "motivation", "spectacular", "confidence", "imagination", "exploration", "tradition",
    "leadership", "photograph", "incredible", "performance", "achievement", "scientist", "understood", "revolution",
    "attention", "collection", "community", "condition", "conversation", "development", "direction", "electricity",
    "emergency", "equipment", "excellent", "government", "important", "improvement", "influence", "information",
    "inspection", "instruction", "intelligence", "interesting", "investment", "management", "marketing", "measurement",
    "membership", "necessary", "operation", "opportunity", "organization", "ownership", "participate", "passenger",
    "personality", "population", "practical", "preparation", "presentation", "production", "protection", "relationship",
    "researcher", "resolution", "restaurant", "selection", "situation", "statement", "strengthen", "successful",
    "suggestion", "suspicious", "television", "temporary", "territory", "traditionally", "transport", "understanding",
    "volunteer", "yesterday", "accomplish", "adjustment", "advertising", "agriculture", "anniversary", "appearance",
    "appreciate", "architect", "assignment", "assistance", "authority", "background", "basketball", "beginning",
    "breakfast", "butterfly", "candidate", "carefully", "character", "chemistry", "childhood", "chocolate",
    "cigarette", "classroom", "comfortable", "committee", "competition", "complicated", "computers", "conclusion",
    "connection", "conscious", "consideration", "construction", "continent", "contractor", "controversy", "convenient",
    "cooperation", "countryside", "criticism", "curiosity", "customers", "decoration", "dedicated", "definition",
    "democracy", "department", "dependent", "depression", "description", "desperate", "determine", "different",
    "difficult", "dimension", "disappear", "disappoint", "discipline", "discussion", "distribute", "documentary",
    "economics", "effective", "efficient", "elementary", "embarrass", "emotional", "encourage", "engineer",
    "entertain", "environment", "essential", "everybody", "evolution", "examination", "exception", "exciting",
    "executive", "exhausted", "expensive", "expertise", "explaining", "expression", "extension", "extensive",
    "familiar", "favorites", "financial", "fireplace", "following", "forgotten", "foundation", "furniture",
    "gathering", "generous", "gradually", "grandfather", "grandmother", "guarantee", "halloween", "handwriting",
    "headquarters", "healthcare", "highlight", "historical", "hopefully", "household", "identical", "ignorance",
    "illustrate", "immediate", "immigrant", "implement", "incentive", "including", "incorrect", "independence",
    "individual", "industrial", "infection", "inflation", "initiative", "institute", "insurance", "integrity",
    "intention", "interface", "interfere", "interview", "introduce", "invention", "invisible", "irrigation",
    "judgement", "knowledgeable", "laboratory", "languages", "legislation", "librarian", "listening", "literature",
    "machinery", "mainstream", "maintains", "manufacturing", "marvelous", "materials", "mathematics", "mechanical",
    "memorable", "microwave", "minority", "miraculous", "misunderstanding", "monument", "motorcycle", "musician",
    "naturally", "neighborhood", "newspaper", "nutrition", "objective", "observing", "obviously", "occasion",
    "offensive", "operating", "opposition", "optimistic", "orchestra", "originally", "packaging", "painfully",
    "paragraph", "parliament", "particular", "passionate", "pavements", "penicillin", "perfection", "permanent",
    "philosophy", "physical", "placement", "playground", "pleasantly", "political", "pollution", "portfolio",
    "potential", "pregnancy", "president", "privilege", "procedure", "professor", "promotion", "publisher",
    "punishment", "purchasing", "qualified", "questionnaire", "realistic", "reception", "recognize", "recommend",
    "recording", "reduction", "reference", "reflection", "refreshing", "regularly", "rejection", "religious",
    "remarkable", "reputation", "requirement", "residence", "resources", "retirement", "satellite", "satisfied",
    "scattered", "scientists", "sculpture", "secretary", "sensitive", "separation", "signature", "similarly",
    "sincerely", "sophisticated", "specialist", "spiritual", "spotlight", "stability", "strategic", "structure",
    "submarine", "substance", "summarize", "sunflower", "supermarket", "surprised", "surrender", "suspense",
    "symphony", "technical", "telephone", "telescope", "terminate", "testimony", "theoretical", "tournament",
    "translate", "treatment", "tremendous", "typically", "unbelievable", "uncertain", "uncomfortable", "unlimited",
    "vacation", "vegetable", "viewpoint", "voluntary", "warehouse", "waterfall", "weaknesses", "wildlife",
    "workplace", "worldwide"
]

var data = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac dignissim diam. Sed quam leo, tempus at vulputate eget, dignissim ac quam. Donec egestas maximus ex sit amet malesuada. Ut facilisis vitae justo nec congue. Donec non tortor ante. Vivamus porta elit nibh, eu consectetur nisl dignissim iaculis. Ut vel finibus nisi.

Sed magna mi, auctor ac enim sit amet, venenatis imperdiet lectus. Donec volutpat sapien vel urna lobortis scelerisque. Nullam mollis sapien sed arcu sagittis iaculis. Phasellus pharetra tellus tempus hendrerit rhoncus. Morbi lobortis diam eu leo finibus pellentesque. Cras sit amet mauris mollis, commodo purus at, mollis nisi. Integer odio eros, laoreet vel risus in, ultricies ultricies nisl. Fusce commodo lorem in erat tincidunt venenatis. Vivamus ullamcorper consectetur nisl. Suspendisse potenti. Mauris placerat erat tortor.

Pellentesque ornare mi eu lectus venenatis, sit amet ultricies diam cursus. Nunc sit amet consequat felis, sed luctus arcu. Nulla facilisi. Nunc posuere ex dolor, a pretium odio imperdiet eu. Fusce congue blandit nibh quis tempus. Ut congue, nisi vel gravida cursus, purus lorem scelerisque tellus, non tincidunt lacus mauris nec quam. Donec ut nunc sapien. Nam eget magna id urna hendrerit tristique dapibus et ligula. Curabitur sed ultrices justo, et tempus metus. Quisque consequat, ipsum non blandit elementum, ligula ante ornare dui, quis ultrices purus dolor sit amet arcu. Nulla neque arcu, semper nec consectetur a, porttitor at risus. Morbi dictum viverra velit a aliquet. Pellentesque aliquam pretium porta. Morbi diam ante, efficitur non vehicula a, porta quis augue. Etiam vel est dolor. Morbi ultricies ut risus in iaculis.

Mauris viverra nulla sed mi condimentum, non tincidunt dui pharetra. Cras tellus velit, commodo in tortor ac, pretium molestie lorem. Nulla rhoncus libero vitae magna consectetur mattis eget eget mi. Donec odio mauris, efficitur ut semper vitae, ullamcorper eu ipsum. Fusce at dignissim mi, quis cursus nisi. Phasellus ullamcorper orci justo, sit amet efficitur purus posuere a. Pellentesque nulla sem, placerat nec enim accumsan, tempus dignissim orci. Integer vitae pharetra neque, sed consectetur velit. Donec quam ligula, vestibulum ac posuere eu, dapibus nec quam. Sed facilisis, est quis ullamcorper tristique, erat ipsum finibus lacus, vel pharetra odio neque quis odio. Maecenas elementum, sapien ac hendrerit tincidunt, purus tellus suscipit augue, et faucibus lacus ligula ac mauris. Sed interdum at mi nec rhoncus.

In hac habitasse platea dictumst. Fusce gravida aliquam mauris, lobortis viverra tellus hendrerit nec. Phasellus ornare vitae magna sed luctus. Integer pulvinar non ipsum eget tincidunt. Integer suscipit massa vitae ex posuere euismod. Cras efficitur ante erat, ac mattis massa luctus et. Curabitur commodo ligula sed feugiat luctus. Donec luctus, nunc in placerat congue, diam ipsum auctor mi, in finibus magna massa nec turpis. Nulla neque est, tempus eget accumsan a, ultricies nec ipsum. Nullam non pulvinar mi, ut convallis mauris. Suspendisse fringilla nulla ex, sit amet pretium purus pulvinar et. Etiam non enim a dolor consequat aliquet. Nam scelerisque urna quis risus dignissim commodo. Cras tincidunt dolor sapien, vel eleifend sapien suscipit eu. Aliquam finibus feugiat augue ultrices dictum.`
